version: '3'
services:
  test:
    build: 
      context: .
      dockerfile: dockerfile-test
    volumes:
      - ./app:/home_recommender/app
    restart: "no"
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=${COMPOSE_CONVERT_WINDOWS_PATHS:?err}
      - COMPUTERNAME=${COMPUTERNAME:?err}
      - USERNAME=${USERNAME:?err}
      - USERDOMAIN=${USERDOMAIN:?err}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:?err}
      - SENTRY_DSN=${HOME_RECOMMENDER_SENTRY_DSN:?err}

  prod:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    environment:
      - COMPUTERNAME=${COMPUTERNAME:?err}
      - USERNAME=${USERNAME:?err}
      - USERDOMAIN=${USERDOMAIN:?err}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:?err}
      - SENTRY_DSN=${HOME_RECOMMENDER_SENTRY_DSN:?err}